### ISSUE TITLE
Add a screenshot to the toplevel README

### ISSUE THREAD

**Issue by fmauch** [UniversalRobots/Universal_Robots_ROS_as_a_Service_URCap#9]
As a better entrypoint, it might be good to get a screenshot of the urcap in action to the toplevel README. I think, we could use this one:

![image](https://github.com/UniversalRobots/Universal_Robots_ROS_as_a_Service_URCap/raw/master/doc/resources/tutorial/13.png)

**Comment by urrsk** [comment]
Good idea :-)
If this also supports the turtle tutorial?

**Comment by fmauch** [comment]
Closing, as implemented in #15
